# Generated by Django 5.2 on 2025-05-22 09:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_variant_size_remove_variant_stock'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'variant', 'size')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
    ]
