# Generated by Django 5.2 on 2025-06-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_usage_limit_alter_coupon_valid_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit',
        ),
    ]
