# Generated by Django 5.2 on 2025-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_is_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('order_placed', 'Order Placed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('return_denied', 'Return_denied')], default='processing', max_length=20),
        ),
    ]
