# Generated by Django 5.2 on 2025-05-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discounted_price',
        ),
    ]
