# Generated by Django 5.2 on 2025-04-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
