# Generated by Django 5.2 on 2025-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variant_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
