# Generated by Django 5.2 on 2025-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_variant_is_default_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_images/'),
        ),
    ]
