# Generated by Django 5.2 on 2025-05-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='stock',
        ),
    ]
