# Generated by Django 5.2 on 2025-05-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
    ]
